# https://jam.dev/blog/automating-chrome-extension-publishing/
name: Update Chrome Extension

on: workflow_dispatch
#  push:
#    branches:
#    - main

jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
          
      - name: Build
        run: |-
          pnpm install
          pnpm build

      - name: Zip extension files 
        run: |
          cd .output/chrome-mv3/ \
          zip -r chrome-extension-${{ github.sha }}.zip .output/chrome-mv3/

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.sha }}.zip
          
  # api usage reference:
  # * <https://developer.chrome.com/docs/webstore/using_webstore_api/>
  # * <https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md>
  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-chrome-extension
    env:
      # you can optionally specify extension ID here, we do this so that
      # all of our environments (dev, staging, prod) have a consistent ID
      # we can reference. Otherwise the extension ID is autogenerated.
      EXTENSION_ID: hlecingfnjghblaegbicfejhghbladkn

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Download bundle artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: chrome-extension-${{ github.sha }}

      - name: Install webstore cli
        run: |-
          npm install -g chrome-webstore-upload-cli

      - name: Upload step
        run: |-
          chrome-webstore-upload upload \
            --source chrome-extension-${{ github.sha }}.zip
        env:
          CLIENT_ID: ${{ secrets.CI_GOOGLE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CI_GOOGLE_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
